//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        public string AnalysisCoefficient { get; set; }
        public string DifficultyCoefficient { get; set; }
        public long ID { get; set; }
        public string InstallationCoefficient { get; set; }
        public int JuniorMinimum { get; set; }
        public int MiddleMinimum { get; set; }
        public int SeniorMinimum { get; set; }
        public string SupportCoefficient { get; set; }
        public System.DateTime TimeCoefficient { get; set; }
        public int ToMoneyCoefficient { get; set; }
        public int Attribute_index { get; set; }
    
        public virtual Userss Userss { get; set; }
    }
}
